FROM golang:1.19-alpine AS builder
RUN apk add build-base

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY ./cmd/skyfish ./cmd/skyfish
COPY ./pkg ./pkg

RUN ls -l

ARG GOFLAGS
RUN go build $GOFLAGS -trimpath -mod=readonly ./cmd/skyfish

#-------------------------------------------------------------------

FROM alpine
MAINTAINER Ian Davis <ian.davis@protocol.ai>

COPY --from=builder /app/skyfish /app/skyfish
COPY --from=builder /etc/ssl/certs /etc/ssl/certs

CMD [ "/app/skyfish"]
